apiVersion: apps/v1
kind: Deployment
metadata:
  name: orm-frontend
  labels:
    app: orm-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orm-frontend
  template:
    metadata:
      labels:
        app: orm-frontend
    spec:
      containers:
        - name: orm-frontend
          image: anyijonathan/node-app:de30ae0c5d5e2d6d3c90265d296a5f68b9f047c6
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: orm-frontend-secrets
          resources:
            requests:
              memory: 300Mi
              cpu: 300m
            limits:
              memory: 500Mi
              cpu: 400m
