name: Docker Image CI

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: anyijonathan
          DOCKER_PASSWORD: Jonathan10.
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag anyijonathan/node-app:${{ github.sha }}

      - name: Docker Push
        run: docker push anyijonathan/node-app:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIA47CR24VEDTFP3DJE
          aws-secret-access-key: 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
          aws-region: us-east-1

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EKS

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: "v1.24.0"
        id: install

      - name: Update kube config
        run: aws eks update-kubeconfig --name eks-cluster-1

      - name: auth to dockerhub
        run: |
          kubectl create secret docker-registry docker-cred \
          --docker-server=https://index.docker.io/v1/ \
          --docker-username=anyijonathan \
          --docker-password=Jonathan10.

      - name: Deploy to EKS
        run: |
          cd kube
          kubectl apply -f deployment.yaml
