name: Docker Image CI

on:
  push:
    branches:
      - development

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: anyijonathan
        DOCKER_PASSWORD: Jonathan10.
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag anyijonathan/node-app:${{ github.sha }}
      
    - name: Docker Push
      run: docker push anyijonathan/node-app:${{ github.sha }}
     
    

  deploy:
    runs-on: ubuntu-latest
    steps:
    

    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: set env for tagging image
      run: |
        tag = git rev-parse HEAD   
        echo tag

    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.24.0'
      id: install

    

  

       

    
        
      

      
